CREATE TABLE public.t_group (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	group_name varchar(255) NULL,
	CONSTRAINT t_group_pkey PRIMARY KEY (id)
);

CREATE TABLE public.t_user (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username varchar(255) NULL,
	group_id int8 NULL,
	CONSTRAINT t_user_pkey PRIMARY KEY (id)
);
ALTER TABLE public.t_user ADD CONSTRAINT t_user_group_id_fk FOREIGN KEY (group_id) REFERENCES public.t_group(id);

INSERT INTO public.t_group(group_name)
  SELECT format('g%s', i)
  FROM generate_series(1, 1000000) as i
;

INSERT INTO public.t_user(username, group_id)
  SELECT format('u%s%s', i, j), i
  FROM generate_series(1, 1000000) AS i
  CROSS JOIN generate_series(1, 10) AS j;